services:
  caddy:
    image: caddy:2

    container_name: spotify_caddy

    restart: unless-stopped

    ports:
      - "3000:3000"

    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro

    depends_on:
      - web